/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDebatePool__factory } from "./IDebatePool__factory";
export { IDebatePoolV2__factory } from "./IDebatePoolV2__factory";
