version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: newscast-debate-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: newscast_debate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - newscast-network

volumes:
  postgres_data:
    driver: local

networks:
  newscast-network:
    driver: bridge
