/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DebatePoolV2 {
  export type PointsAwardStruct = {
    user: AddressLike;
    points: BigNumberish;
    reason: string;
    timestamp: BigNumberish;
    signature: BytesLike;
  };

  export type PointsAwardStructOutput = [
    user: string,
    points: bigint,
    reason: string,
    timestamp: bigint,
    signature: string
  ] & {
    user: string;
    points: bigint;
    reason: string;
    timestamp: bigint;
    signature: string;
  };

  export type WinnerResultStruct = {
    debateId: BigNumberish;
    winner: AddressLike;
    timestamp: BigNumberish;
    signature: BytesLike;
  };

  export type WinnerResultStructOutput = [
    debateId: bigint,
    winner: string,
    timestamp: bigint,
    signature: string
  ] & {
    debateId: bigint;
    winner: string;
    timestamp: bigint;
    signature: string;
  };

  export type DebateStruct = {
    id: BigNumberish;
    topic: string;
    entryFee: BigNumberish;
    maxParticipants: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    participants: AddressLike[];
    winner: AddressLike;
    isActive: boolean;
    isCompleted: boolean;
  };

  export type DebateStructOutput = [
    id: bigint,
    topic: string,
    entryFee: bigint,
    maxParticipants: bigint,
    startTime: bigint,
    endTime: bigint,
    participants: string[],
    winner: string,
    isActive: boolean,
    isCompleted: boolean
  ] & {
    id: bigint;
    topic: string;
    entryFee: bigint;
    maxParticipants: bigint;
    startTime: bigint;
    endTime: bigint;
    participants: string[];
    winner: string;
    isActive: boolean;
    isCompleted: boolean;
  };
}

export interface DebatePoolV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "DEBATE_PARTICIPATION_POINTS"
      | "DEBATE_WINNER_POINTS"
      | "LIKE_POINTS"
      | "PLATFORM_FEE_PERCENTAGE"
      | "REFUND_PERIOD"
      | "SHARE_POINTS"
      | "TIMEOUT_PERIOD"
      | "airdropClaimed"
      | "airdropEnabled"
      | "airdropSnapshotBlock"
      | "airdropToken"
      | "awardLikePoints"
      | "awardPoints"
      | "awardSharePoints"
      | "claimAirdrop"
      | "createDebate"
      | "debates"
      | "declareWinner"
      | "eip712Domain"
      | "emergencyPaused"
      | "emergencyRefund"
      | "getDebate"
      | "getUserDebates"
      | "getUserPoints"
      | "isParticipant"
      | "joinDebate"
      | "nextDebateId"
      | "oracle"
      | "owner"
      | "processExpiredDebate"
      | "refundDeadlines"
      | "renounceOwnership"
      | "requestRefund"
      | "setupAirdrop"
      | "toggleEmergencyPause"
      | "totalAirdropAmount"
      | "transferOwnership"
      | "usdcToken"
      | "userDebates"
      | "userPoints"
      | "withdrawPlatformFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AirdropClaimed"
      | "AirdropSetup"
      | "DebateCreated"
      | "EIP712DomainChanged"
      | "EmergencyPauseToggled"
      | "OwnershipTransferred"
      | "ParticipantJoined"
      | "PointsAwarded"
      | "RefundProcessed"
      | "WinnerDeclared"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEBATE_PARTICIPATION_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEBATE_WINNER_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIKE_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFUND_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHARE_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMEOUT_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "airdropClaimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "airdropEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "airdropSnapshotBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "airdropToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "awardLikePoints",
    values: [DebatePoolV2.PointsAwardStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "awardPoints",
    values: [DebatePoolV2.PointsAwardStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "awardSharePoints",
    values: [DebatePoolV2.PointsAwardStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAirdrop",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createDebate",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "debates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "declareWinner",
    values: [DebatePoolV2.WinnerResultStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDebates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isParticipant",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinDebate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextDebateId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processExpiredDebate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refundDeadlines",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setupAirdrop",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleEmergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAirdropAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userDebates",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userPoints",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEBATE_PARTICIPATION_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEBATE_WINNER_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIKE_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFUND_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SHARE_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMEOUT_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "airdropClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "airdropEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "airdropSnapshotBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "airdropToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "awardLikePoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "awardPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "awardSharePoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "debates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "declareWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDebate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserDebates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinDebate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextDebateId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processExpiredDebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundDeadlines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleEmergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAirdropAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userDebates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userPoints", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
}

export namespace AirdropClaimedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    points: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, points: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    points: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AirdropSetupEvent {
  export type InputTuple = [
    token: AddressLike,
    totalAmount: BigNumberish,
    snapshotBlock: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    totalAmount: bigint,
    snapshotBlock: bigint
  ];
  export interface OutputObject {
    token: string;
    totalAmount: bigint;
    snapshotBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebateCreatedEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    topic: string,
    entryFee: BigNumberish
  ];
  export type OutputTuple = [debateId: bigint, topic: string, entryFee: bigint];
  export interface OutputObject {
    debateId: bigint;
    topic: string;
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyPauseToggledEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantJoinedEvent {
  export type InputTuple = [debateId: BigNumberish, participant: AddressLike];
  export type OutputTuple = [debateId: bigint, participant: string];
  export interface OutputObject {
    debateId: bigint;
    participant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PointsAwardedEvent {
  export type InputTuple = [
    user: AddressLike,
    points: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [user: string, points: bigint, reason: string];
  export interface OutputObject {
    user: string;
    points: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundProcessedEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    participant: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    debateId: bigint,
    participant: string,
    amount: bigint
  ];
  export interface OutputObject {
    debateId: bigint;
    participant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerDeclaredEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    winner: AddressLike,
    prize: BigNumberish
  ];
  export type OutputTuple = [debateId: bigint, winner: string, prize: bigint];
  export interface OutputObject {
    debateId: bigint;
    winner: string;
    prize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DebatePoolV2 extends BaseContract {
  connect(runner?: ContractRunner | null): DebatePoolV2;
  waitForDeployment(): Promise<this>;

  interface: DebatePoolV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  DEBATE_PARTICIPATION_POINTS: TypedContractMethod<[], [bigint], "view">;

  DEBATE_WINNER_POINTS: TypedContractMethod<[], [bigint], "view">;

  LIKE_POINTS: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  REFUND_PERIOD: TypedContractMethod<[], [bigint], "view">;

  SHARE_POINTS: TypedContractMethod<[], [bigint], "view">;

  TIMEOUT_PERIOD: TypedContractMethod<[], [bigint], "view">;

  airdropClaimed: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  airdropEnabled: TypedContractMethod<[], [boolean], "view">;

  airdropSnapshotBlock: TypedContractMethod<[], [bigint], "view">;

  airdropToken: TypedContractMethod<[], [string], "view">;

  awardLikePoints: TypedContractMethod<
    [award: DebatePoolV2.PointsAwardStruct],
    [void],
    "nonpayable"
  >;

  awardPoints: TypedContractMethod<
    [award: DebatePoolV2.PointsAwardStruct],
    [void],
    "nonpayable"
  >;

  awardSharePoints: TypedContractMethod<
    [award: DebatePoolV2.PointsAwardStruct],
    [void],
    "nonpayable"
  >;

  claimAirdrop: TypedContractMethod<
    [
      userPointsAmount: BigNumberish,
      totalPoints: BigNumberish,
      messageHash: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createDebate: TypedContractMethod<
    [
      topic: string,
      entryFee: BigNumberish,
      maxParticipants: BigNumberish,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  debates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        id: bigint;
        topic: string;
        entryFee: bigint;
        maxParticipants: bigint;
        startTime: bigint;
        endTime: bigint;
        winner: string;
        isActive: boolean;
        isCompleted: boolean;
      }
    ],
    "view"
  >;

  declareWinner: TypedContractMethod<
    [result: DebatePoolV2.WinnerResultStruct],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  emergencyPaused: TypedContractMethod<[], [boolean], "view">;

  emergencyRefund: TypedContractMethod<
    [debateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDebate: TypedContractMethod<
    [debateId: BigNumberish],
    [DebatePoolV2.DebateStructOutput],
    "view"
  >;

  getUserDebates: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getUserPoints: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  isParticipant: TypedContractMethod<
    [debateId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  joinDebate: TypedContractMethod<
    [debateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextDebateId: TypedContractMethod<[], [bigint], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processExpiredDebate: TypedContractMethod<
    [debateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  refundDeadlines: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestRefund: TypedContractMethod<
    [debateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setupAirdrop: TypedContractMethod<
    [_airdropToken: AddressLike, _totalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  toggleEmergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  totalAirdropAmount: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  userDebates: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userPoints: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawPlatformFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEBATE_PARTICIPATION_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEBATE_WINNER_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIKE_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFUND_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SHARE_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIMEOUT_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "airdropClaimed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "airdropEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "airdropSnapshotBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "airdropToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "awardLikePoints"
  ): TypedContractMethod<
    [award: DebatePoolV2.PointsAwardStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "awardPoints"
  ): TypedContractMethod<
    [award: DebatePoolV2.PointsAwardStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "awardSharePoints"
  ): TypedContractMethod<
    [award: DebatePoolV2.PointsAwardStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimAirdrop"
  ): TypedContractMethod<
    [
      userPointsAmount: BigNumberish,
      totalPoints: BigNumberish,
      messageHash: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDebate"
  ): TypedContractMethod<
    [
      topic: string,
      entryFee: BigNumberish,
      maxParticipants: BigNumberish,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "debates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        id: bigint;
        topic: string;
        entryFee: bigint;
        maxParticipants: bigint;
        startTime: bigint;
        endTime: bigint;
        winner: string;
        isActive: boolean;
        isCompleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "declareWinner"
  ): TypedContractMethod<
    [result: DebatePoolV2.WinnerResultStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyRefund"
  ): TypedContractMethod<[debateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDebate"
  ): TypedContractMethod<
    [debateId: BigNumberish],
    [DebatePoolV2.DebateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDebates"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserPoints"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isParticipant"
  ): TypedContractMethod<
    [debateId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinDebate"
  ): TypedContractMethod<[debateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextDebateId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processExpiredDebate"
  ): TypedContractMethod<[debateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refundDeadlines"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRefund"
  ): TypedContractMethod<[debateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setupAirdrop"
  ): TypedContractMethod<
    [_airdropToken: AddressLike, _totalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "toggleEmergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAirdropAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userDebates"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userPoints"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AirdropClaimed"
  ): TypedContractEvent<
    AirdropClaimedEvent.InputTuple,
    AirdropClaimedEvent.OutputTuple,
    AirdropClaimedEvent.OutputObject
  >;
  getEvent(
    key: "AirdropSetup"
  ): TypedContractEvent<
    AirdropSetupEvent.InputTuple,
    AirdropSetupEvent.OutputTuple,
    AirdropSetupEvent.OutputObject
  >;
  getEvent(
    key: "DebateCreated"
  ): TypedContractEvent<
    DebateCreatedEvent.InputTuple,
    DebateCreatedEvent.OutputTuple,
    DebateCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyPauseToggled"
  ): TypedContractEvent<
    EmergencyPauseToggledEvent.InputTuple,
    EmergencyPauseToggledEvent.OutputTuple,
    EmergencyPauseToggledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantJoined"
  ): TypedContractEvent<
    ParticipantJoinedEvent.InputTuple,
    ParticipantJoinedEvent.OutputTuple,
    ParticipantJoinedEvent.OutputObject
  >;
  getEvent(
    key: "PointsAwarded"
  ): TypedContractEvent<
    PointsAwardedEvent.InputTuple,
    PointsAwardedEvent.OutputTuple,
    PointsAwardedEvent.OutputObject
  >;
  getEvent(
    key: "RefundProcessed"
  ): TypedContractEvent<
    RefundProcessedEvent.InputTuple,
    RefundProcessedEvent.OutputTuple,
    RefundProcessedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerDeclared"
  ): TypedContractEvent<
    WinnerDeclaredEvent.InputTuple,
    WinnerDeclaredEvent.OutputTuple,
    WinnerDeclaredEvent.OutputObject
  >;

  filters: {
    "AirdropClaimed(address,uint256,uint256)": TypedContractEvent<
      AirdropClaimedEvent.InputTuple,
      AirdropClaimedEvent.OutputTuple,
      AirdropClaimedEvent.OutputObject
    >;
    AirdropClaimed: TypedContractEvent<
      AirdropClaimedEvent.InputTuple,
      AirdropClaimedEvent.OutputTuple,
      AirdropClaimedEvent.OutputObject
    >;

    "AirdropSetup(address,uint256,uint256)": TypedContractEvent<
      AirdropSetupEvent.InputTuple,
      AirdropSetupEvent.OutputTuple,
      AirdropSetupEvent.OutputObject
    >;
    AirdropSetup: TypedContractEvent<
      AirdropSetupEvent.InputTuple,
      AirdropSetupEvent.OutputTuple,
      AirdropSetupEvent.OutputObject
    >;

    "DebateCreated(uint256,string,uint256)": TypedContractEvent<
      DebateCreatedEvent.InputTuple,
      DebateCreatedEvent.OutputTuple,
      DebateCreatedEvent.OutputObject
    >;
    DebateCreated: TypedContractEvent<
      DebateCreatedEvent.InputTuple,
      DebateCreatedEvent.OutputTuple,
      DebateCreatedEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "EmergencyPauseToggled(bool)": TypedContractEvent<
      EmergencyPauseToggledEvent.InputTuple,
      EmergencyPauseToggledEvent.OutputTuple,
      EmergencyPauseToggledEvent.OutputObject
    >;
    EmergencyPauseToggled: TypedContractEvent<
      EmergencyPauseToggledEvent.InputTuple,
      EmergencyPauseToggledEvent.OutputTuple,
      EmergencyPauseToggledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ParticipantJoined(uint256,address)": TypedContractEvent<
      ParticipantJoinedEvent.InputTuple,
      ParticipantJoinedEvent.OutputTuple,
      ParticipantJoinedEvent.OutputObject
    >;
    ParticipantJoined: TypedContractEvent<
      ParticipantJoinedEvent.InputTuple,
      ParticipantJoinedEvent.OutputTuple,
      ParticipantJoinedEvent.OutputObject
    >;

    "PointsAwarded(address,uint256,string)": TypedContractEvent<
      PointsAwardedEvent.InputTuple,
      PointsAwardedEvent.OutputTuple,
      PointsAwardedEvent.OutputObject
    >;
    PointsAwarded: TypedContractEvent<
      PointsAwardedEvent.InputTuple,
      PointsAwardedEvent.OutputTuple,
      PointsAwardedEvent.OutputObject
    >;

    "RefundProcessed(uint256,address,uint256)": TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;
    RefundProcessed: TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;

    "WinnerDeclared(uint256,address,uint256)": TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
    WinnerDeclared: TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
  };
}
