/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { DebatePool } from "./DebatePool";
export type { EmergencyUSDCWithdrawer } from "./EmergencyUSDCWithdrawer";
export type { MockERC20 } from "./MockERC20";
