/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDebatePool {
  export type WinnerResultStruct = {
    debateId: BigNumberish;
    winner: AddressLike;
    timestamp: BigNumberish;
    signature: BytesLike;
  };

  export type WinnerResultStructOutput = [
    debateId: bigint,
    winner: string,
    timestamp: bigint,
    signature: string
  ] & {
    debateId: bigint;
    winner: string;
    timestamp: bigint;
    signature: string;
  };

  export type DebateStruct = {
    id: BigNumberish;
    topic: string;
    entryFee: BigNumberish;
    maxParticipants: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    participants: AddressLike[];
    winner: AddressLike;
    isActive: boolean;
    isCompleted: boolean;
  };

  export type DebateStructOutput = [
    id: bigint,
    topic: string,
    entryFee: bigint,
    maxParticipants: bigint,
    startTime: bigint,
    endTime: bigint,
    participants: string[],
    winner: string,
    isActive: boolean,
    isCompleted: boolean
  ] & {
    id: bigint;
    topic: string;
    entryFee: bigint;
    maxParticipants: bigint;
    startTime: bigint;
    endTime: bigint;
    participants: string[];
    winner: string;
    isActive: boolean;
    isCompleted: boolean;
  };
}

export interface IDebatePoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createDebate"
      | "declareWinner"
      | "getActiveDebates"
      | "getDebate"
      | "joinDebate"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DebateCreated"
      | "FundsWithdrawn"
      | "ParticipantJoined"
      | "WinnerDeclared"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createDebate",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "declareWinner",
    values: [IDebatePool.WinnerResultStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveDebates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDebate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "joinDebate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createDebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "declareWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveDebates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDebate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinDebate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace DebateCreatedEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    topic: string,
    entryFee: BigNumberish
  ];
  export type OutputTuple = [debateId: bigint, topic: string, entryFee: bigint];
  export interface OutputObject {
    debateId: bigint;
    topic: string;
    entryFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantJoinedEvent {
  export type InputTuple = [debateId: BigNumberish, participant: AddressLike];
  export type OutputTuple = [debateId: bigint, participant: string];
  export interface OutputObject {
    debateId: bigint;
    participant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerDeclaredEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    winner: AddressLike,
    prize: BigNumberish
  ];
  export type OutputTuple = [debateId: bigint, winner: string, prize: bigint];
  export interface OutputObject {
    debateId: bigint;
    winner: string;
    prize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDebatePool extends BaseContract {
  connect(runner?: ContractRunner | null): IDebatePool;
  waitForDeployment(): Promise<this>;

  interface: IDebatePoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createDebate: TypedContractMethod<
    [
      topic: string,
      entryFee: BigNumberish,
      maxParticipants: BigNumberish,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  declareWinner: TypedContractMethod<
    [result: IDebatePool.WinnerResultStruct],
    [void],
    "nonpayable"
  >;

  getActiveDebates: TypedContractMethod<[], [bigint[]], "view">;

  getDebate: TypedContractMethod<
    [debateId: BigNumberish],
    [IDebatePool.DebateStructOutput],
    "view"
  >;

  joinDebate: TypedContractMethod<
    [debateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createDebate"
  ): TypedContractMethod<
    [
      topic: string,
      entryFee: BigNumberish,
      maxParticipants: BigNumberish,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "declareWinner"
  ): TypedContractMethod<
    [result: IDebatePool.WinnerResultStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveDebates"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getDebate"
  ): TypedContractMethod<
    [debateId: BigNumberish],
    [IDebatePool.DebateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinDebate"
  ): TypedContractMethod<[debateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DebateCreated"
  ): TypedContractEvent<
    DebateCreatedEvent.InputTuple,
    DebateCreatedEvent.OutputTuple,
    DebateCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantJoined"
  ): TypedContractEvent<
    ParticipantJoinedEvent.InputTuple,
    ParticipantJoinedEvent.OutputTuple,
    ParticipantJoinedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerDeclared"
  ): TypedContractEvent<
    WinnerDeclaredEvent.InputTuple,
    WinnerDeclaredEvent.OutputTuple,
    WinnerDeclaredEvent.OutputObject
  >;

  filters: {
    "DebateCreated(uint256,string,uint256)": TypedContractEvent<
      DebateCreatedEvent.InputTuple,
      DebateCreatedEvent.OutputTuple,
      DebateCreatedEvent.OutputObject
    >;
    DebateCreated: TypedContractEvent<
      DebateCreatedEvent.InputTuple,
      DebateCreatedEvent.OutputTuple,
      DebateCreatedEvent.OutputObject
    >;

    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "ParticipantJoined(uint256,address)": TypedContractEvent<
      ParticipantJoinedEvent.InputTuple,
      ParticipantJoinedEvent.OutputTuple,
      ParticipantJoinedEvent.OutputObject
    >;
    ParticipantJoined: TypedContractEvent<
      ParticipantJoinedEvent.InputTuple,
      ParticipantJoinedEvent.OutputTuple,
      ParticipantJoinedEvent.OutputObject
    >;

    "WinnerDeclared(uint256,address,uint256)": TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
    WinnerDeclared: TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
  };
}
