apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: battle-completion-worker
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1
      timeoutSeconds: 3600
      containers:
      - image: gcr.io/PROJECT_ID/battle-completion-worker:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: battle-worker-secrets
              key: database-url
        - name: GOOGLE_GENERATIVE_AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: battle-worker-secrets
              key: google-api-key
        - name: SERPER_API_KEY
          valueFrom:
            secretKeyRef:
              name: battle-worker-secrets
              key: serper-api-key
        - name: CURRENTS_API_KEY
          valueFrom:
            secretKeyRef:
              name: battle-worker-secrets
              key: currents-api-key
        - name: NEWS_SOURCE
          value: "serper"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
